config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  # root 'teams#index'
  resources :teams
  devise_for :trainers
  resources :profile, only: [:show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pokemon.rb
class Pokemon < ApplicationRecord
  belongs_to :team
  validates :name, presence: true

  before_save :verify_quantity_team

  private

  def verify_quantity_team
    if team.pokemons.count > 6
      errors[:base] << I18n.t(:maximum_pokemon_team, scope: 'activerecord.errors.models.pokemon')
    end
  end
end

app/models/team.rb
class Team < ApplicationRecord
  belongs_to :trainer
  has_many :pokemons, dependent: :delete_all

  accepts_nested_attributes_for :pokemons

  validates :name, presence: true
end

app/models/trainer.rb
class Trainer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :lockable, :timeoutable, and :omniauthable, :confirmable,
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :trackable

  validates :name, presence: true

  enum gender: %i[male female other]

  has_many :teams, dependent: :delete_all

  has_one_attached :picture
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_trainer!

  include Pundit
  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  layout :layout_by_resource
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[name age gender picture])
    devise_parameter_sanitizer.permit(:account_update, keys: %i[name age gender picture])
  end

  private

  def layout_by_resource
    if devise_controller? && !devise_registration_edit_view?
      'login'
    else
      'application'
    end
  end

  def devise_registration_edit_view?
    request.fullpath.match?('/trainers/edit') || (request.fullpath.match('/trainers') && params[:action] == 'update')
  end

  # PUNDIT: Change current_user to current_trainer
  def pundit_user
    current_trainer
  end

  def user_not_authorized
    flash[:alert] = I18n.t(:you_are_not_authorized_to_perform_this_action)
    redirect_to(request.referer || home_path)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :authenticate_trainer!, only: [:index]
  def index; end
end

app/controllers/profile_controller.rb
class ProfileController < ApplicationController
  before_action :set_trainer, only: %i[show]
  def show; end

  private

  def set_trainer
    @trainer = Trainer.find(params[:id])
  end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  before_action :set_team, only: %i[show edit update destroy]
  before_action :get_pokedex, only: %i[new edit create update]

  # GET /teams or /teams.json
  def index
    authorize Team, :index?
    @teams = current_trainer.teams
  end

  # GET /teams/1 or /teams/1.json
  def show
    authorize @team, :show?
  end

  # GET /teams/new
  def new
    @team = Team.new
    @team.pokemons.build
    authorize @team, :new?
  end

  # GET /teams/1/edit
  def edit
    authorize @team, :edit?
  end

  # POST /teams or /teams.json
  def create
    @team = Team.new(team_params)
    authorize @team, :create?
    params[:team][:pokemons_attributes].each do |_index, pokemon|
      next if pokemon['name'].blank?

      pokeapi = GetPokedex.new(pokemon['name']).get_pokemon
      @pokemon = @team.pokemons.new(name: pokeapi['name'],
                                    sprite_url: pokeapi['sprites']['front_default'])
      types_pokemon = ''
      pokeapi['types'].each do |type|
        types_pokemon += "#{type['type']['name']} "
      end
      @pokemon.type_pokemon = types_pokemon
    end
    @team.trainer = current_trainer

    if @team.save
      redirect_to @team, notice: t(:created, model: t(:team, scope: 'activerecord.models'))
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /teams/1 or /teams/1.json
  def update
    authorize @team, :update?
    if @team.update(team_params)
      redirect_to @team, notice: t(:updated, model: t(:team, scope: 'activerecord.models'))
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /teams/1 or /teams/1.json
  def destroy
    authorize @team, :destroy?
    @team.destroy
    redirect_to teams_url, notice: t(:deleted, model: t(:team, scope: 'activerecord.models'))
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_team
    @team = Team.find(params[:id])
  end

  def get_pokedex
    @pokedex = GetPokedex.new.get_pokedex
  end

  # Only allow a list of trusted parameters through.
  def team_params
    # params.require(:team).permit(:name, pokemons_attributes: [:name])
    params.require(:team).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def title(title_string)
    content_for :title do
      title_string
    end
  end

  def link_to_back(path)
    render 'shared/link_to_back', path: path
  end

  def link_to_new_resource(path, title = nil)
    render 'shared/link_to_new_resource', title: title, path: path
  end

  def link_to_edit_resource(path, title = nil)
    render 'shared/link_to_edit_resource', title: title, path: path
  end

  def link_to_detail_resource(path, title = nil)
    render 'shared/link_to_detail_resource', title: title, path: path
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/views/home/index.html.erb
  <div class="jumbotron">
    <h1>Time de Pokemons</h1>
    <h3>Venha criar seu time com até 6 jogadores!</h3>
    <p><%= link_to "Entre para ver os times", new_trainer_registration_path, class: "btn btn-info btn-lg" %></p>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>PokeTeam</title>
  <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
      <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
      <link rel="stylesheet" media="all"
        href="https://gitcdn.github.io/bootstrap-toggle/2.2.2/css/bootstrap-toggle.min.css"
        data-turbolinks-track="true" />
      <script src="https://gitcdn.github.io/bootstrap-toggle/2.2.2/js/bootstrap-toggle.min.js"></script>

      <%= stylesheet_link_tag 'application' , media: 'all' , 'data-turbolinks-track': 'reload' %>
        <%= javascript_include_tag 'application' , 'data-turbolinks-track': 'reload' %>

        <nav class="navbar navbar-expand-lg navbar navbar navbar-dark bg-dark">
          <div class="container-fluid">
            <a class="navbar-brand" href="#">POKETEAM</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarScroll" aria-controls="navbarScroll" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarScroll">
              <ul class="navbar-nav me-auto my-2 my-lg-0 navbar-nav-scroll" style="--bs-scroll-height: 100px;">
                <li class="nav-item">
                  <%= link_to t(:Times, scope: 'menu'), teams_path, class: "nav-link #{'active' if controller_path == 'teams'}" %>
                </li>
                <% if current_trainer %>
                  <li class="nav-item ">
                    <%= link_to profile_path(current_trainer), class: "nav-link #{'active' if controller_path == 'profile'}" do %>
                      <%= current_trainer.name %>
                    <% end %>
                  </li>
                  <% end %>
              </ul>
            <% if trainer_signed_in? %>  
              <li class="d-flex">
                <%= button_to destroy_trainer_session_path, method: :delete, class: 'nav-link btn' do %>
                  <%= t(:Sair, scope: 'menu.dropdown') %>
                <% end %>
              </li>
            <% end %>
            </div>
          </div>
        </nav>
</head>

<body>
  <%= yield %>
</body>


</html>

app/views/layouts/login.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PokeTeam</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />

		<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700" />

    <%= stylesheet_link_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container pt-3">
      <div class="row mt-5">
        <div class="col-sm-12 col-md-7 mx-auto bg-light p-5" style="border-radius: 30px; box-shadow: 1px 1px 20px rgba(0,0,0,.3)">
          <%= yield %>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/shared/_flashes.html.erb
<% flash.each do |name, msg| %>
  <div class="alert-container">
    <div class="alert alert-top alert-<%= name.to_s == 'notice' ? "success" : "danger" %>">
      <a class="close" data-dismiss="alert">&times;</a>
      <%= msg %>
    </div>
  </div>
<% end %>

app/views/shared/_link_to_back.html.erb
<%= content_for :right do -%>
  <%= link_to t(:back), path, class: 'btn btn-outline-primary btn-fixed-height font-weight-bold px-2 px-lg-5 mr-2' %>
<%- end %>

app/views/shared/_link_to_detail_resource.html.erb
<%= content_for :right do -%>
  <%= link_to title || t(:show), path, class: "btn btn-outline-primary btn-fixed-height font-weight-bold px-2 px-lg-5 mr-2" %>
<% end -%>

app/views/shared/_link_to_edit_resource.html.erb
<%= content_for :right do -%>
  <%= link_to title || t(:edit), path, class: "btn btn-outline-primary btn-fixed-height font-weight-bold px-2 px-lg-5 mr-2" %>
<% end -%>

app/views/shared/_link_to_new_resource.html.erb
<%= content_for :right do -%>
  <%= link_to title, path, class: "btn btn-outline-primary btn-fixed-height font-weight-bold px-2 px-lg-5 mr-2" %>
<% end -%>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-md d-flex navbar-dark bg-primary">
  <a class="navbar-brand" href="#"><%= t(:webapp_slogan) %></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav ml-auto">
      <li class="nav-item">
        <%= link_to t(:home, scope: 'menu'), root_path, class: "nav-link #{'active' if controller_path == 'home'}" %>
      </li>
      <li class="nav-item">
        <%= link_to t(:teams, scope: 'menu'), teams_path, class: "nav-link #{'active' if controller_path == 'teams'}" %>
      </li>
      <% if current_trainer %>
        <li class="nav-item ">
          <%= link_to profile_path(current_trainer), class: "nav-link #{'active' if controller_path == 'profile'}" do %>
            <%= current_trainer.name %>
          <% end %>
        </li>
        <li class="nav-item dropdown">
          <%= button_to destroy_trainer_session_path, method: :delete, class: 'nav-link btn' do %>
            <%= t(:logout, scope: 'menu.dropdown') %>
          <% end %>
        </li>

      <% end %>
    </ul>
  </div>
</nav>

app/views/trainers/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/trainers/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to t(:sign_in, scope: "devise.links"), new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to t(:sign_up, scope: "devise.links"), new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to t(:forgot_your_password, scope: "devise.links"), new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to t(:did_not_receive_confirmation_instructions, scope: "devise.links"), new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to t(:did_not_receive_unlock_instructions, scope: "devise.links"), new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to t(:sign_in_with, scope: "devise.links", provider: OmniAuth::Utils.camelize(provider)), omniauth_authorize_path(resource_name, provider) %><br />
  <% end %> 
<% end %>